language: node_js
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

deploy:
  provider: pages
  cleanup: true
  github-token: $travis
  local_dir: public
  on:
    branch: master
